### ISSUE TITLE
cgcloud create -IT toil-latest-box error

### ISSUE THREAD

**Issue by dyollluap** [BD2KGenomics/cgcloud#90] opened 2016-01-21 00:45 UTC
Failed to create a new image, error message:

[52.33.196.59] sudo: pip install --pre s3am
[52.33.196.59] out: stdin: is not a tty
[52.33.196.59] out: Collecting s3am
[52.33.196.59] out:   Downloading s3am-1.0b1.dev38.tar.gz
[52.33.196.59] out: Collecting pycurl==7.21.5 (from s3am)
[52.33.196.59] out:   Downloading pycurl-7.21.5.tar.gz (170kB)
[52.33.196.59] out: Collecting boto==2.38.0 (from s3am)
[52.33.196.59] out:   Downloading boto-2.38.0-py2.py3-none-any.whl (1.3MB)
[52.33.196.59] out: Installing collected packages: pycurl, boto, s3am
[52.33.196.59] out:   Found existing installation: pycurl 7.19.3
[52.33.196.59] out: Detected a distutils installed project ('pycurl') which we cannot uninstall. The metadata provided by distutils does not contain a list of files which have been installed, so pip does not know which files to uninstall.
[52.33.196.59] out: 

Fatal error: sudo() received nonzero return code 1 while executing!

Requested: pip install --pre s3am
Executed: sudo -S -p 'sudo password:'  -H /bin/bash -l -c "pip install --pre s3am"

Aborting.
INFO: Terminating instance ...

**Comment by dyollluap** [comment] 2016-01-21 00:47
and does this terminated image creation overwrite my previous image?

**Comment by hannes-ucsc** [comment] 2016-01-21 06:13
No, it does not.

**Comment by hannes-ucsc** [comment] 2016-01-21 06:15
Looks like @adderan beat you to it :-)

Closing as duplicate of #89.

**Closed as completed by hannes-ucsc** 2016-01-21 06:15 UTC
Labels: duplicate
